// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2bQuJrhlXKA1K_9tfIKvfNFqohweoRy8',
    appId: '1:299251458125:android:cc3b4d2a89e0e9d11b3c04',
    messagingSenderId: '299251458125',
    projectId: 'notes-db180',
    storageBucket: 'notes-db180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcyfAMeGzByOfOs9cpAguhC9OdnFlYj24',
    appId: '1:299251458125:ios:cfcfeb3222782cc01b3c04',
    messagingSenderId: '299251458125',
    projectId: 'notes-db180',
    storageBucket: 'notes-db180.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgy3mnIots618idS8iQDcMxu6S1zqBraI',
    appId: '1:299251458125:web:4a703df8d04375f31b3c04',
    messagingSenderId: '299251458125',
    projectId: 'notes-db180',
    authDomain: 'notes-db180.firebaseapp.com',
    storageBucket: 'notes-db180.appspot.com',
    measurementId: 'G-G11DW2RMM1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcyfAMeGzByOfOs9cpAguhC9OdnFlYj24',
    appId: '1:299251458125:ios:cfcfeb3222782cc01b3c04',
    messagingSenderId: '299251458125',
    projectId: 'notes-db180',
    storageBucket: 'notes-db180.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgy3mnIots618idS8iQDcMxu6S1zqBraI',
    appId: '1:299251458125:web:f6307eddf08a8a601b3c04',
    messagingSenderId: '299251458125',
    projectId: 'notes-db180',
    authDomain: 'notes-db180.firebaseapp.com',
    storageBucket: 'notes-db180.appspot.com',
    measurementId: 'G-WRTL3KNMJV',
  );

}